/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOptions {
  react: ReactOptions
}
export interface ReactOptions {
  jsxPlugin: boolean
  runtime: ReactJsxRuntime
}
export const enum ReactJsxRuntime {
  Classic = 0,
  Automatic = 1
}
export interface SourceMap {
  file?: string
  names: Array<string>
  sourceRoot?: string
  sources: (string | null)[]
  sourcesContent?: (string | null)[]
  version: number
  ignoreList?: Array<number>
  mappings: string
}
export interface TransformResult {
  sourceText: string
  sourceMap?: SourceMap
}
export function transform(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
export function transformAsync(filename: string, sourceText: string, options?: TransformOptions | undefined | null): Promise<TransformResult>
