/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */


import type { CompressOption } from './options'

export interface TransformOptions {
  react: ReactOptions
  codegen: MinifyOptions
}
export interface MinifyOptions {
  compress: CompressOption | boolean
  sourceMap: boolean
}
export interface ReactOptions {
  jsxPlugin: boolean
  runtime: ReactJsxRuntime
}
export const enum ReactJsxRuntime {
  Classic = 0,
  Automatic = 1
}
/**
 * should match
 * [`EncodedSourceMap`](https://github.com/jridgewell/trace-mapping/blob/5a658b10d9b6dea9c614ff545ca9c4df895fee9e/src/types.ts#L14)
 * from `@jridgewell/trace-mapping`, since this is what Jest expects.
 * ```ts
 * export interface SourceMapV3 {
 *   file?: string | null;
 *   names: string[];
 *   sourceRoot?: string;
 *   sources: (string | null)[];
 *   sourcesContent?: (string | null)[];
 *   version: 3;
 *   ignoreList?: number[];
 * }
 *
 * export interface EncodedSourceMap extends SourceMapV3 {
 *   mappings: string;
 * }
 * ```
 */
export interface SourceMap {
  file?: string
  names: Array<string>
  sourceRoot?: string
  sources: (string | null)[]
  sourcesContent?: (string | null)[]
  version: number
  ignoreList?: Array<number>
  mappings: string
}
export interface TransformResult {
  sourceText: string
  sourceMap?: SourceMap
}
export declare function transform(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
export declare function transformAsync(filename: string, sourceText: string, options?: TransformOptions | undefined | null): Promise<TransformResult>

export type { CompressOption }
