name: CI

on:
    push:
        branches: [main]
        paths-ignore:
            - '**/*.md'
            - '**/*.yml'
            - '!.github/workflows/ci.yml'
    pull_request:
        branches: [main]
        types: [opened, synchronize]
        paths-ignore:
            - '**/*.md'
            - '**/*.yml'
            - '!.github/workflows/ci.yml'

env:
    NODE_VERSION: 22

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
            - uses: Boshen/setup-rust@main
              with:
                  # warm cache factory for all other CI jobs
                  # cache `target` directory to avoid download crates
                  save-cache: ${{ github.ref_name == 'main' }}
                  cache-key: warm
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'
            - run: yarn --no-immutable
            - run: cargo check
            # gets done by yarn build, but `yarn workspaces run` suppresses
            # output and this is a good way to check for errors. Cached results
            # will be used in following step.
            - run: yarn napi build
              working-directory: napi/transform
            - run: yarn build:debug
            # FIXME: yarn.lock always changes
            # - run: git diff --exit-code
